### ISSUE TITLE
Error on saving the solution 

### ISSUE THREAD

**Issue by rohithakosuru** [icsharpcode/NRefactory#538]
System.NotImplementedException: The method or operation is not implemented.
   at ICSharpCode.NRefactory.VB.Visitors.CSharpToVBConverterVisitor.VisitUncheckedStatement(UncheckedStatement uncheckedStatement, Object data)
   at ICSharpCode.NRefactory.VB.Visitors.CSharpToVBConverterVisitor.ConvertNodes[T](IEnumerable`1 nodes, AstNodeCollection`1 result, Func`2 transform)
   at ICSharpCode.NRefactory.VB.Visitors.CSharpToVBConverterVisitor.VisitBlockStatement(BlockStatement blockStatement, Object data)
   at ICSharpCode.NRefactory.VB.Visitors.CSharpToVBConverterVisitor.VisitForStatement(ForStatement forStatement, Object data)
   at ICSharpCode.NRefactory.VB.Visitors.CSharpToVBConverterVisitor.ConvertNodes[T](IEnumerable`1 nodes, AstNodeCollection`1 result, Func`2 transform)
   at ICSharpCode.NRefactory.VB.Visitors.CSharpToVBConverterVisitor.VisitBlockStatement(BlockStatement blockStatement, Object data)
   at ICSharpCode.NRefactory.VB.Visitors.CSharpToVBConverterVisitor.VisitCheckedStatement(CheckedStatement checkedStatement, Object data)
   at ICSharpCode.NRefactory.VB.Visitors.CSharpToVBConverterVisitor.ConvertNodes[T](IEnumerable`1 nodes, AstNodeCollection`1 result, Func`2 transform)
   at ICSharpCode.NRefactory.VB.Visitors.CSharpToVBConverterVisitor.VisitBlockStatement(BlockStatement blockStatement, Object data)
   at ICSharpCode.NRefactory.VB.Visitors.CSharpToVBConverterVisitor.VisitMethodDeclaration(MethodDeclaration methodDeclaration, Object data)
   at ICSharpCode.NRefactory.VB.Visitors.CSharpToVBConverterVisitor.ConvertMembers[T,S,M](AstNode parent, T result, Role`1 sourceRole, Role`1 targetRole)
   at ICSharpCode.NRefactory.VB.Visitors.CSharpToVBConverterVisitor.VisitTypeDeclaration(TypeDeclaration typeDeclaration, Object data)
   at ICSharpCode.NRefactory.VB.Visitors.CSharpToVBConverterVisitor.ConvertMembers[T,S,M](AstNode parent, T result, Role`1 sourceRole, Role`1 targetRole)
   at ICSharpCode.NRefactory.VB.Visitors.CSharpToVBConverterVisitor.VisitNamespaceDeclaration(NamespaceDeclaration namespaceDeclaration, Object data)
   at ICSharpCode.NRefactory.VB.Visitors.CSharpToVBConverterVisitor.VisitSyntaxTree(SyntaxTree syntaxTree, Object data)
   at ICSharpCode.ILSpy.VB.VBLanguage.RunTransformsAndGenerateCode(AstBuilder astBuilder, ITextOutput output, DecompilationOptions options, ModuleDefinition module)
   at ICSharpCode.ILSpy.VB.VBLanguage.<>c__DisplayClass15_0.<WriteCodeFilesInProject>b__2(IGrouping`2 file)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)

**Comment by lextm** [comment]
You really should read the Readme file once again, as it said "If you need a C# parser / compiler frontend, use Microsoft.CodeAnalysis (Roslyn) instead."

**Comment by siegfriedpammer** [comment]
@lextm looking at the bottom of the stack trace this is an error produced by an old version of ILSpy, which still had VB support. So actually, it should be reported at https://github.com/icsharpcode/ILSpy/issues but we cannot do anything about the error anyway because ILSpy 2.x is long out of support and all ILSpy versions > 2 do not have VB support anymore. It is unsupported.
